version: '2'

services:
 php:
   volumes:
     - ${SYMFONY_APP_PATH}:/usr/src/app

 nginx:
   volumes:
     - ${SYMFONY_APP_PATH}public/:/usr/src/app
     - './nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
   ports:
     - '${NGINX_PORT}:80'

 adminer:
   ports:
     - '${ADMINER_PORT}:8080'